In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
cd gdrive/My Drive/airplane

/content/gdrive/My Drive/airplane


In [0]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
import tensorflow as tf

Using TensorFlow backend.


In [0]:
!pip3 install --upgrade tensorflow

Requirement already up-to-date: tensorflow in /usr/local/lib/python3.6/dist-packages (2.1.0)


In [0]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [0]:
train_data.head()

Severity  ...  Accident_ID
0                Minor_Damage_And_Injuries  ...         7570
1                Minor_Damage_And_Injuries  ...        12128
2        Significant_Damage_And_Fatalities  ...         2181
3  Significant_Damage_And_Serious_Injuries  ...         5946
4        Significant_Damage_And_Fatalities  ...         9054

[5 rows x 12 columns]

In [0]:
test_data.head()

Safety_Score  Days_Since_Inspection  ...  Adverse_Weather_Metric  Accident_ID
0     19.497717                     16  ...                0.069692            1
1     58.173516                     15  ...                0.002777           10
2     33.287671                     15  ...                0.004316           14
3      3.287671                     21  ...                0.199990           17
4     10.867580                     18  ...                0.483696           21

[5 rows x 11 columns]

In [0]:
train_data = train_data.drop(columns = ['Accident_ID'])

In [0]:
train_data.head()

Severity  ...  Adverse_Weather_Metric
0                Minor_Damage_And_Injuries  ...                0.424352
1                Minor_Damage_And_Injuries  ...                0.352350
2        Significant_Damage_And_Fatalities  ...                0.003364
3  Significant_Damage_And_Serious_Injuries  ...                0.211728
4        Significant_Damage_And_Fatalities  ...                0.176883

[5 rows x 11 columns]

In [0]:
atc = train_data.values[:,7]
atc = atc -  1
atcu = np.unique(atc)
atcu

array([0, 1, 2, 3, 4, 5, 6], dtype=object)

In [0]:
atctc = np_utils.to_categorical(atc)

In [0]:
atctc[0]

array([0., 1., 0., 0., 0., 0., 0.], dtype=float32)

In [0]:
Y = train_data.values[:,0]
classes = np.unique(Y)

In [0]:
classes

array(['Highly_Fatal_And_Damaging', 'Minor_Damage_And_Injuries',
       'Significant_Damage_And_Fatalities',
       'Significant_Damage_And_Serious_Injuries'], dtype=object)

In [0]:
class_dict = {'Highly_Fatal_And_Damaging':0, 'Minor_Damage_And_Injuries':1,
       'Significant_Damage_And_Fatalities':2,
       'Significant_Damage_And_Serious_Injuries':3}

In [0]:
index_dict = {0:'Highly_Fatal_And_Damaging',1:'Minor_Damage_And_Injuries',2:'Significant_Damage_And_Fatalities',3:'Significant_Damage_And_Serious_Injuries'}

In [0]:
y = np.array([class_dict[i] for i in Y])

In [0]:
y = np_utils.to_categorical(y)

In [0]:
y[:10]

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [0]:
y.shape

(10000, 4)

In [0]:
train_data = train_data.drop(columns = ['Accident_Type_Code'])
X = train_data.values[:,1:]

In [0]:
X.shape

(10000, 9)

In [0]:
Xt = np.hstack((X, atctc))
Xt.shape

(10000, 16)

In [0]:
Xt[0]

array([49.2237442922374, 14, 22, 71.285323609845, 0.272117562206996,
       78.04, 31335.4768243775, 3, 0.42435208330785296, 0.0, 1.0, 0.0,
       0.0, 0.0, 0.0, 0.0], dtype=object)

In [0]:
actT = test_data.values[:,6]
actTu = np.unique(actT)
actTu = actTu - 1
actTct = np_utils.to_categorical(actT-1)
XT = test_data.drop(columns = ['Accident_Type_Code']).values[:,:-1]
XTT = np.hstack((XT , actTct))

In [0]:
XTT[0]

array([1.94977169e+01, 1.60000000e+01, 6.00000000e+00, 7.21513218e+01,
       3.88958529e-01, 7.83200000e+01, 3.79497244e+04, 2.00000000e+00,
       6.96924473e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [0]:
acc_ids[1]

10.0

In [0]:
XTT.shape

(2500, 16)

In [0]:
X2 = Xt
XT2 = XTT

In [0]:
for i in range(9):

  t_mean = X[:,i].mean(axis = 0)
  t_std = X[:,i].std(axis = 0)
  X2[:, i] = (X[:,i] - t_mean)/t_std
  XT2[:,i] = (XT[: , i] - t_mean)/t_std 

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X2, y ,test_size = 0.2)

In [0]:
X_train = np.array(X_train , dtype= 'float16')
X_test = np.asarray(X_test , dtype = 'float16')
y_train = np.asarray(y_train , dtype = 'int')
y_test = np.asarray(y_test , dtype = 'int')

In [0]:
X_train[0]

array([-0.2664, -0.828 ,  0.78  ,  0.4016, -0.616 , -0.2498,  1.1045,
        0.9497, -0.4688,  0.    ,  0.    ,  0.    ,  1.    ,  0.    ,
        0.    ,  0.    ], dtype=float16)

In [0]:
y_train[0]

array([1, 0, 0, 0])

In [0]:
es = tf.keras.callbacks.EarlyStopping(monitor = 'accuracy')
optimizer = tf.keras.optimizers.Adadelta()

In [0]:
input_layer = tf.keras.layers.Input((11,))

In [0]:
model1 = tf.keras.models.Sequential()
model1.add(tf.keras.layers.Dense(6 , input_shape = (16,)))
model1.add(tf.keras.layers.Dense(10,activation = 'relu'))
model1.add(tf.keras.layers.Dropout(0.3))
model1.add(tf.keras.layers.Dense(4 , activation = 'softmax'))
model1.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' , metrics = ['accuracy'])
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 102       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                70        
_________________________________________________________________
dropout (Dropout)            (None, 10)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 44        
Total params: 216
Trainable params: 216
Non-trainable params: 0
_________________________________________________________________


In [0]:
history1 = model1.fit(X_train, y_train, batch_size  = 200, epochs = 500 ,  validation_data = [X_test, y_test] , shuffle= True)

Train on 8000 samples, validate on 2000 samples
Epoch 1/500
8000/8000 [==============================] - 2s 247us/sample - loss: 1.4711 - accuracy: 0.2841 - val_loss: 1.3934 - val_accuracy: 0.3365
Epoch 2/500
8000/8000 [==============================] - 0s 19us/sample - loss: 1.3911 - accuracy: 0.3429 - val_loss: 1.3356 - val_accuracy: 0.3780
Epoch 3/500
8000/8000 [==============================] - 0s 21us/sample - loss: 1.3303 - accuracy: 0.3689 - val_loss: 1.2881 - val_accuracy: 0.4135
Epoch 4/500
8000/8000 [==============================] - 0s 21us/sample - loss: 1.2859 - accuracy: 0.4053 - val_loss: 1.2442 - val_accuracy: 0.4550
Epoch 5/500
8000/8000 [==============================] - 0s 19us/sample - loss: 1.2506 - accuracy: 0.4252 - val_loss: 1.2008 - val_accuracy: 0.4905
Epoch 6/500
8000/8000 [==============================] - 0s 20us/sample - loss: 1.2130 - accuracy: 0.4505 - val_loss: 1.1555 - val_accuracy: 0.5260
Epoch 7/500
8000/8000 [==============================] - 0s 20u

In [0]:
ss = pd.read_csv('sample_submission.csv')

In [0]:
test_predictions1 = model1.predict(XT2)

In [0]:
test_predictions1[:5]

array([[9.99972105e-01, 3.54412277e-10, 4.16944310e-08, 2.78898769e-05],
       [1.16517951e-08, 4.04071179e-04, 9.98762488e-01, 8.33429105e-04],
       [1.06888376e-01, 8.32626969e-02, 1.11065898e-03, 8.08738291e-01],
       [9.99857187e-01, 1.43277816e-08, 1.15651819e-05, 1.31185690e-04],
       [4.62458223e-01, 5.23232757e-06, 5.37534118e-01, 2.40763848e-06]],
      dtype=float32)

In [0]:
ss.head()

Accident_ID                                 Severity
0            1                Minor_Damage_And_Injuries
1           10                Highly_Fatal_And_Damaging
2           14                Highly_Fatal_And_Damaging
3           17  Significant_Damage_And_Serious_Injuries
4           21                Minor_Damage_And_Injuries

In [0]:
model2 = tf.keras.models.Sequential()
model2.add(tf.keras.layers.Dense(12 , input_shape = (16,)))
model2.add(tf.keras.layers.Dense(16 , activation = 'relu'))
model2.add(tf.keras.layers.Dropout(0.3))
model2.add(tf.keras.layers.Dense(8 , activation = 'relu'))
model2.add(tf.keras.layers.Dense(4, activation = 'softmax'))
model2.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' , metrics = ['accuracy'])
model2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 12)                204       
_________________________________________________________________
dense_8 (Dense)              (None, 16)                208       
_________________________________________________________________
dropout_2 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_10 (Dense)             (None, 4)                 36        
Total params: 584
Trainable params: 584
Non-trainable params: 0
_________________________________________________________________


In [0]:
history2 = model2.fit(X_train, y_train, batch_size  = 300, epochs = 6000 ,  validation_data = [X_test, y_test] ,shuffle = True)

Train on 8000 samples, validate on 2000 samples
Epoch 1/6000
8000/8000 [==============================] - 0s 17us/sample - loss: 0.2620 - accuracy: 0.9103 - val_loss: 0.1872 - val_accuracy: 0.9450
Epoch 2/6000
8000/8000 [==============================] - 0s 15us/sample - loss: 0.2570 - accuracy: 0.9143 - val_loss: 0.1862 - val_accuracy: 0.9460
Epoch 3/6000
8000/8000 [==============================] - 0s 15us/sample - loss: 0.2667 - accuracy: 0.9154 - val_loss: 0.1906 - val_accuracy: 0.9425
Epoch 4/6000
8000/8000 [==============================] - 0s 15us/sample - loss: 0.2571 - accuracy: 0.9168 - val_loss: 0.1860 - val_accuracy: 0.9455
Epoch 5/6000
8000/8000 [==============================] - 0s 15us/sample - loss: 0.2582 - accuracy: 0.9151 - val_loss: 0.1886 - val_accuracy: 0.9460
Epoch 6/6000
8000/8000 [==============================] - 0s 16us/sample - loss: 0.2530 - accuracy: 0.9161 - val_loss: 0.1888 - val_accuracy: 0.9450
Epoch 7/6000
8000/8000 [==============================] - 

In [0]:
test_predictions2 = model2.predict(XT2)

In [0]:
model3 = tf.keras.models.Sequential()
model3.add(tf.keras.layers.Dense(20 , input_shape = (10,)))
model3.add(tf.keras.layers.Dense(32 , activation = 'relu'))
model3.add(tf.keras.layers.Dropout(0.3))
model3.add(tf.keras.layers.Dense(12 , activation = 'relu'))
model3.add(tf.keras.layers.Dense(4, activation = 'softmax'))
model3.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' , metrics = ['accuracy'])
model3.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_8 (Dense)              (None, 32)                672       
_________________________________________________________________
dropout_2 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_9 (Dense)              (None, 12)                396       
_________________________________________________________________
dense_10 (Dense)             (None, 4)                 52        
Total params: 1,340
Trainable params: 1,340
Non-trainable params: 0
_________________________________________________________________


In [0]:
history3 = model3.fit(X_train, y_train, batch_size  = 200, epochs = 500 ,  validation_data = [X_test, y_test] ,shuffle=True)

Train on 8000 samples, validate on 2000 samples
Epoch 1/500
8000/8000 [==============================] - 0s 29us/sample - loss: 1.4812 - acc: 0.2562 - val_loss: 1.3417 - val_acc: 0.2945
Epoch 2/500
8000/8000 [==============================] - 0s 18us/sample - loss: 1.3274 - acc: 0.3315 - val_loss: 1.2414 - val_acc: 0.3995
Epoch 3/500
8000/8000 [==============================] - 0s 18us/sample - loss: 1.2292 - acc: 0.4189 - val_loss: 1.1307 - val_acc: 0.5165
Epoch 4/500
8000/8000 [==============================] - 0s 18us/sample - loss: 1.1140 - acc: 0.5086 - val_loss: 1.0061 - val_acc: 0.5935
Epoch 5/500
8000/8000 [==============================] - 0s 17us/sample - loss: 1.0087 - acc: 0.5711 - val_loss: 0.8847 - val_acc: 0.6635
Epoch 6/500
8000/8000 [==============================] - 0s 16us/sample - loss: 0.8995 - acc: 0.6305 - val_loss: 0.7670 - val_acc: 0.7160
Epoch 7/500
8000/8000 [==============================] - 0s 18us/sample - loss: 0.7992 - acc: 0.6865 - val_loss: 0.6579 - va

In [0]:
test_predictions3 = model3.predict(XT2)

In [0]:
model4 = tf.keras.models.Sequential()
model4.add(tf.keras.layers.Dense(18 , input_shape = (10,)))
model4.add(tf.keras.layers.Dense(24 , activation = 'relu'))
model4.add(tf.keras.layers.Dropout(0.3))
model4.add(tf.keras.layers.Dense(16 , activation = 'relu'))
model4.add(tf.keras.layers.Dense(10, activation = 'relu'))
model4.add(tf.keras.layers.Dropout(0.3))
model4.add(tf.keras.layers.Dense(4 , activation = 'softmax'))
model4.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' , metrics = ['accuracy'])
model4.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 18)                198       
_________________________________________________________________
dense_17 (Dense)             (None, 24)                456       
_________________________________________________________________
dropout_5 (Dropout)          (None, 24)                0         
_________________________________________________________________
dense_18 (Dense)             (None, 16)                400       
_________________________________________________________________
dense_19 (Dense)             (None, 10)                170       
_________________________________________________________________
dropout_6 (Dropout)          (None, 10)                0         
_________________________________________________________________
dense_20 (Dense)             (None, 4)                

In [0]:
history4 = model4.fit(X_train, y_train, batch_size  = 150, epochs = 500 ,  validation_data = [X_test, y_test] ,shuffle = True)

Train on 8000 samples, validate on 2000 samples
Epoch 1/500
8000/8000 [==============================] - 0s 50us/sample - loss: 1.4070 - acc: 0.2876 - val_loss: 1.3123 - val_acc: 0.3945
Epoch 2/500
8000/8000 [==============================] - 0s 22us/sample - loss: 1.3190 - acc: 0.3498 - val_loss: 1.2431 - val_acc: 0.4265
Epoch 3/500
8000/8000 [==============================] - 0s 22us/sample - loss: 1.2612 - acc: 0.3810 - val_loss: 1.1503 - val_acc: 0.5020
Epoch 4/500
8000/8000 [==============================] - 0s 21us/sample - loss: 1.1693 - acc: 0.4526 - val_loss: 1.0057 - val_acc: 0.5805
Epoch 5/500
8000/8000 [==============================] - 0s 21us/sample - loss: 1.0714 - acc: 0.5023 - val_loss: 0.8933 - val_acc: 0.6605
Epoch 6/500
8000/8000 [==============================] - 0s 24us/sample - loss: 0.9986 - acc: 0.5322 - val_loss: 0.8058 - val_acc: 0.7215
Epoch 7/500
8000/8000 [==============================] - 0s 24us/sample - loss: 0.9283 - acc: 0.5819 - val_loss: 0.7086 - va

In [0]:
test_predictions4 = model4.predict(XT2)

In [0]:
ensemble_preds = [np.argmax((test_predictions2[i] + test_predictions3[i] + test_predictions4[i])/3) for i in range(XT2.shape[0])]

In [0]:
ensemble_preds[:5]

[0, 2, 3, 0, 2]

In [0]:
answer_column = [index_dict[i] for i in ensemble_preds]

In [0]:
d = {'Accident_ID' : acc_ids , 'Severity' : answer_column}

In [0]:
submission_df = pd.DataFrame(d)

In [0]:
submission_df = submission_df.set_index(['Accident_ID'])

In [0]:
submission_df.to_csv('ensemble_predictions.csv')

In [0]:
model5 = tf.keras.models.Sequential()
model5.add(tf.keras.layers.Dense(12 , input_shape = (10,)))
model5.add(tf.keras.layers.Dense(18 , activation = 'relu'))
model5.add(tf.keras.layers.Dropout(0.4))
model5.add(tf.keras.layers.Dense(10, activation = 'relu'))
model5.add(tf.keras.layers.Dense(4 , activation = 'softmax'))
model5.compile(optimizer = 'adam' , loss = 'categorical_crossentropy' , metrics = ['accuracy'])
model5.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 12)                132       
_________________________________________________________________
dense_26 (Dense)             (None, 18)                234       
_________________________________________________________________
dropout_8 (Dropout)          (None, 18)                0         
_________________________________________________________________
dense_27 (Dense)             (None, 10)                190       
_________________________________________________________________
dense_28 (Dense)             (None, 4)                 44        
Total params: 600
Trainable params: 600
Non-trainable params: 0
_________________________________________________________________


In [0]:
history5 = model5.fit(X_train, y_train, batch_size  = 150, epochs = 500 ,  validation_data = [X_test, y_test] ,shuffle = True)

Train on 8000 samples, validate on 2000 samples
Epoch 1/500
8000/8000 [==============================] - 0s 51us/sample - loss: 1.4353 - acc: 0.2920 - val_loss: 1.3191 - val_acc: 0.3585
Epoch 2/500
8000/8000 [==============================] - 0s 22us/sample - loss: 1.3353 - acc: 0.3429 - val_loss: 1.2600 - val_acc: 0.4215
Epoch 3/500
8000/8000 [==============================] - 0s 21us/sample - loss: 1.2740 - acc: 0.3837 - val_loss: 1.1860 - val_acc: 0.4755
Epoch 4/500
8000/8000 [==============================] - 0s 22us/sample - loss: 1.2106 - acc: 0.4435 - val_loss: 1.1041 - val_acc: 0.5410
Epoch 5/500
8000/8000 [==============================] - 0s 24us/sample - loss: 1.1354 - acc: 0.5054 - val_loss: 1.0145 - val_acc: 0.6300
Epoch 6/500
8000/8000 [==============================] - 0s 22us/sample - loss: 1.0481 - acc: 0.5767 - val_loss: 0.9144 - val_acc: 0.6870
Epoch 7/500
8000/8000 [==============================] - 0s 21us/sample - loss: 0.9753 - acc: 0.6173 - val_loss: 0.8264 - va

In [0]:
test_predictions5 = model5.predict(XT2)

In [0]:
model6 = tf.keras.models.Sequential()
model6.add(tf.keras.layers.Dense(64 , input_shape = (10,)))
model6.add(tf.keras.layers.Dense(32 , activation = 'relu'))
model6.add(tf.keras.layers.Dropout(0.4))
model6.add(tf.keras.layers.Dense(16 , activation = 'relu'))
model6.add(tf.keras.layers.Dense(24 ,activation = 'relu'))
model6.add(tf.keras.layers.Dropout(0.4))
model6.add(tf.keras.layers.Dense(12 , activation = 'relu'))
model6.add(tf.keras.layers.Dense(4 , activation  ='softmax'))
model6.compile(optimizer = 'adagrad',  loss='categorical_crossentropy' , metrics = ['accuracy'])

In [0]:
history6 = model6.fit(X_train , y_train , batch_size = 100 , epochs = 5000 , validation_data = [X_test, y_test], shuffle = True)

Train on 8000 samples, validate on 2000 samples
Epoch 1/5000
8000/8000 [==============================] - 0s 33us/sample - loss: 0.4288 - acc: 0.8606 - val_loss: 0.2797 - val_acc: 0.9205
Epoch 2/5000
8000/8000 [==============================] - 0s 37us/sample - loss: 0.4340 - acc: 0.8547 - val_loss: 0.2797 - val_acc: 0.9205
Epoch 3/5000
8000/8000 [==============================] - 0s 38us/sample - loss: 0.4291 - acc: 0.8593 - val_loss: 0.2796 - val_acc: 0.9205
Epoch 4/5000
8000/8000 [==============================] - 0s 40us/sample - loss: 0.4331 - acc: 0.8553 - val_loss: 0.2796 - val_acc: 0.9205
Epoch 5/5000
8000/8000 [==============================] - 0s 37us/sample - loss: 0.4251 - acc: 0.8584 - val_loss: 0.2796 - val_acc: 0.9205
Epoch 6/5000
8000/8000 [==============================] - 0s 39us/sample - loss: 0.4292 - acc: 0.8551 - val_loss: 0.2796 - val_acc: 0.9210
Epoch 7/5000
8000/8000 [==============================] - 0s 40us/sample - loss: 0.4298 - acc: 0.8556 - val_loss: 0.27

In [0]:
test_predictions6 = model6.predict(XT2)

In [0]:
ensemble_preds = [np.argmax((test_predictions2[i] + test_predictions3[i] + test_predictions4[i]+test_predictions5[i] + test_predictions6[i])/5) for i in range(XT2.shape[0])]

In [0]:
answer_column = [index_dict[i] for i in ensemble_preds]

In [0]:
d = {'Accident_ID' : acc_ids , 'Severity' : answer_column}

In [0]:
submission_df = pd.DataFrame(d)

In [0]:
submission_df =submission_df.set_index(['Accident_ID'])

In [0]:
submission_df.to_csv('ensemble_predictions2.csv')